opam-version: "2.0"
maintainer: "skylee03"
homepage: "https://github.com/skylee03/stlc-semantic-typing"
dev-repo: "git+https://github.com/skylee03/stlc-semantic-typing.git"
bug-reports: "https://github.com/skylee03/stlc-semantic-typing/issues"
license: "MIT"
authors: ["skylee03"]
depends: [
  "coq" {>= "9.0"}
  "coq-hammer" {with-dev-setup & >= "1.3.2"}
  "coq-hammer-tactics" {>= "1.3.2"}
  "dune" {>= "3.17"}
  "rocq-autosubst-ocaml" {>= "1.1"}
  "rocq-equations" {>= "1.3.1"}
  "rocq-prover" {>= "9.0"}
  "rocq-stdpp"
]
synopsis: "STLC Semantic Typing"
